feat:Gestion de  lista de Reproduccion (Issue #18)
TheJose24/EuphonyApp-Backend pull request #22
Opened 2024-10-22 18:49 UTC by Anthonysystemas

Se desarrolló la API para gestionar las playlists de usuarios.

Se implementaron los servicios y lógica CRUD para playlists.

Se crearon DTOs específicos para request/response de playlists.

Se manejaron excepciones (PlaylistNotFoundException)

Se documentó la API con Swagger incluyendo los endpoints de playlist.

2024-10-22 19:35 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/service/interfaces/IPlaylistService.java
Solo se retorna un responseDTO cuando se hace un consulta

2024-10-22 19:36 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/service/interfaces/IPlaylistService.java
> +    PlaylistResponseDTO updatePlaylist(Long id, PlaylistRequestDTO playlistRequestDTO);
Retornar Void

2024-10-22 19:37 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/service/interfaces/IPlaylistService.java
Solo se retorna un responseDTO cuando se hace una consulta

2024-10-22 19:37 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/service/interfaces/IPlaylistService.java
> +    PlaylistResponseDTO createPlaylist(PlaylistRequestDTO playlistRequestDTO);
Retornar Void y no PlaylistResponseDTO

2024-10-22 19:37 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/service/interfaces/IPlaylistService.java
> +    PlaylistResponseDTO updatePlaylist(Long id, PlaylistRequestDTO playlistRequestDTO);
Retornar Void y no PlaylistResponseDTO

2024-10-22 19:38 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/service/interfaces/IPlaylistService.java
> +    PlaylistResponseDTO removeSongFromPlaylist(Long playlistId, Long cancionId);
Retornar Void y no PlaylistResponseDTO

2024-10-22 19:39 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/service/interfaces/IPlaylistService.java
> +    PlaylistResponseDTO addSongToPlaylist(Long playlistId, Long cancionId);
Retornar Void y no PlaylistResponseDTO

2024-10-22 19:40 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/service/implementation/PlaylistServiceImpl.java
Usar logs

2024-10-22 19:41 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/exception/custom/PlaylistException.java
Atrapar la exepcion en el `GlobalExeptionHandler`

2024-10-22 19:46 UTC, TheJose24 requested changes
Corregir manejo de excepciones y retorno de DTOs correctos,

2024-10-24 15:39 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/controller/PlaylistController.java
>      private final IPlaylistService playlistService;
Debes usar la implementación, no la interfaz.

2024-10-24 15:42 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/dto/request/PlaylistRequestDTO.java
Documentación en español.

2024-10-24 15:43 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/dto/response/PlaylistResponseDTO.java
Documentación en español.

2024-10-24 15:53 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/exception/custom/PlaylistSongException.java
Debe nombrarse `SonException`

2024-10-24 15:54 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/service/interfaces/IPlaylistService.java
Comentar en español.

2024-10-24 15:56 UTC, TheJose24 commented on src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandlerPlaylist.java
ExceptionHandler innecesario.

2024-10-24 15:57 UTC, TheJose24 approved these changes

2024-10-24 15:58 UTC, TheJose24 requested changes
Corregir comentarios y ExeptionHandler innecesario

2024-10-25 13:23 UTC, Anthonysystemas commented on src/main/java/com/euphony/streaming/dto/request/PlaylistRequestDTO.java
ok

2024-10-31 21:22 UTC, closed without merging